name: My CI
on:
  push:
    branches:
      - master
jobs:
  igor-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install composer dependencies
      run: composer install
    - name: Run unit tests via PHPUnit
      run: ./vendor/bin/phpcs